# Generated by Django 4.1.5 on 2023-01-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('locationn', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('non IT', 'non IT'), ('other', 'other')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
