# Generated by Django 4.1.5 on 2023-01-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('startlocation', models.CharField(max_length=50)),
                ('endlocation', models.EmailField(max_length=20)),
                ('dateTime', models.DateTimeField()),
                ('noOfAsset', models.IntegerField()),
                ('assetType', models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('TRAVEL_BAG', 'TRAVEL_BAG'), ('PACKAGE', 'PACKAGE')], max_length=50)),
                ('assetSensitivity', models.CharField(choices=[('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'), ('SENSITIVE', 'SENSITIVE'), ('NORMAL', 'NORMAL')], max_length=50)),
                ('delivery', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TravelInfo',
            fields=[
                ('traveler_id', models.AutoField(primary_key=True, serialize=False)),
                ('startlocation', models.CharField(max_length=50)),
                ('endlocation', models.EmailField(max_length=20)),
                ('dateTime', models.DateTimeField()),
                ('travel_medium', models.CharField(choices=[('BUS', 'BUS'), ('CAR', 'CAR'), ('TRAIN', 'TRAIN')], max_length=50)),
            ],
        ),
    ]
