# Generated by Django 4.1.5 on 2023-01-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='UserDetails',
        ),
    ]
