# Generated by Django 4.1.5 on 2023-01-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_userdetail_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userdetails'),
        ),
    ]
