# Generated by Django 4.1.5 on 2023-01-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_asset_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='user_id',
            new_name='UserName',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='locationn',
            new_name='location',
        ),
    ]
