# Generated by Django 4.1.5 on 2023-01-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_id_asset_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='conpany',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
